# This workflow uses actions that are not certified by GitHub. They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
#
# Aqua Security Trivy: Comprehensive vulnerability scanner
# <https://github.com/aquasecurity/trivy-action>

name: Trivy

permissions:
  security-events: write
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate debug keystore
        run: keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"

      - name: Build the app
        run: ./gradlew assembleDebug                                 # Update this to build your Android or iOS application

      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'report.sarif'

      - name: Upload SARIF to GHAS
        if: always() && hashFiles('report.sarif') != ''
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: report.sarif
